name: Docker deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup-docker
      uses: docker-practice/actions-setup-docker@0.0.1
      with:
        # Docker Version
        docker_version: 19.03 # optional, default is 19.03
        # Docker Channel
        docker_channel: stable # optional, default is stable
    - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u vla9isla8 --password-stdin
    - run: docker build . -t docker.pkg.github.com/vla9isla8/coursera-machine-lerning-env/jupiter:latest
    - run: docker push docker.pkg.github.com/vla9isla8/coursera-machine-lerning-env/jupiter:latest
      env:
        CI: true
